### PR TITLE
Attempt to separate python annotator from Python extension

### PR DESCRIPTION
**Pull request by tmjoris**
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-XXXX

**What's in the PR**
* A new directory  calles changes in the python directory which contains new files python_annotator.cpp, python_modules.cpp and a Makefile which builds them. These are files extracted from splitting pythonnator.cpp.

**How to test manually**
* Building the DLLs using the make commands then checking if the DLLs (_python_annotator.so and _python_modules.so) are generated in your directory, and finally using make clean to verify their clean up.

**Automatic testing**
* [ ] PR adds/updates unit tests -no

**Documentation**
* [ ] PR adds/updates documentation -no

**Organizational**
- [ ] PR includes new dependencies.   -no
      <sub><sup>Only dependencies under [approved licenses](http://www.apache.org/legal/resolved.html#category-a) are allowed. LICENSE and NOTICE files in the respective modules where dependencies have been added as well as in the project root have been updated.</sup></sub>

### CODE REVIEW

**Comment by tmjoris** [comment]
@DrDub have a look at the PR and tell me where it can be enhanced, I am adding you as an editor into my proposal today hope it's not too late. This is the PR in relation to problem #8, and yes I had success building the SDK with your improved documentation

**Comment by DrDub** [comment]
Hi! I feel there was some miscommunication, I wasn't expecting you to work on this. But if it _does_ work it will be fantastic :-)

I see the template needs editing to refer to the GitHub issues rather than the JIRA ticket.

This will take me a while to review.

From the top of it, why are you working on a "changes" folder? That seems wrong.

Have you ever signed a ICLA with the foundation? https://www.apache.org/licenses/contributor-agreements.html
(put to notify the UIMA project if you do). If you have an employer that might need a CCLA but I'll need to check for that, too.

I'll have to check whether this contribution requires one (most probably all of them do).

**Comment by DrDub** [comment]
I got further clarification in the mailing list. You won't need ICLA for this particular pull request, it is covered by Sec. 5 from the Apache License.

**Comment by reckart** [comment]
You can still provide an ICLA though - it will facilitate further contributions to this or other projects at the ASF.

**Comment by tmjoris** [comment]
@DrDub, @reckart I found the ICLA in a link in the site provided earlier, should I sign it now and send to secretary@apache.org

**Comment by tmjoris** [comment]
And also I am planning on modifying my GitHub actions for the Docker image, just got notified that I'm using a deprecated version of node. That rendered it unable to run

**Comment by reckart** [comment]
@tmjoris ICLAs should be sent **only** to the secretary. In particular, do not post a CLA to github or public mailing lists to avoid sharing Personal Identifiable Information (PII). Make sure to mention the UIMA project on the ICLA so that the secretary can notify us about the filed ICLA. Also please mention your GitHub ID is mentioned on the ICLA even if there is no field for it on the ICLA form - in particular if your GitHub ID differs from any Apache ID you might request.

**Comment by reckart** [comment]
General advice: when you create a pull request, make sure to create a branch in your forked repo first, e.g. `refactoring/16-Attempt-to-separate-python-annotator-from-Python-extension` make your changes on that branch and then open the PR for that branch. That allows you to work on multiple contributions in parallel and makes things more convenient for maintainers / collaborators to work with your branch (e.g. it will not conflict with the `main` branch in our own clones).

Look at how commit messages are in general written in the repo and apply the same style when writing your own messages. E.g. we typically use  a format like:

```
Issue #NUMBER: ISSUE TITLE

- change 1
- change 2
- change 3
- ...
```

Check that the commit author name is properly configured in your git to include your name and email address. If you use multiple computers, check that all of them are configured in the same way. In particular, the name and mail address should match the information from the ICLA.

**Comment by tmjoris** [comment]
thanks @reckart
Your advice and instructions are noted

**Pull request closed without merging**
